title: 'JJTS Web Streaming & Broadcast'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.25
  brandStrength: 0.1875
  lightness: 0.5340502
  brandColors:
    - '#001295'
    - '#405cfe'
    - '#f0f2fe'
    - '#7a87f9'
    - '#404560'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-70674872-1
  facebook: null
name: JJTS-Streaming
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.45403
layout_spectrum: 0.44338
