name: JJTS-Streaming
favicon: null
layout_spectrum: 0.25127
typography_spectrum: 0.45403
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001295'
    - '#405cfe'
    - '#f0f2fe'
    - '#7a87f9'
    - '#404560'
  brandStrength: 0.5625
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
