name: JJTS-Streaming
favicon: null
layout_spectrum: 1
typography_spectrum: 0.45403
title: 'JJTS Web Streaming & Broadcast'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001295'
    - '#405cfe'
    - '#f0f2fe'
    - '#7a87f9'
    - '#404560'
  brandStrength: 0.125
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
