name: JJTS-Streaming
favicon: null
layout_spectrum: 0.32304
typography_spectrum: 0.45403
title: 'JJTS Web Streaming & Broadcast'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70674872-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001295'
    - '#405cfe'
    - '#f0f2fe'
    - '#7a87f9'
    - '#404560'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
