name: JJTS-Streaming
favicon: null
layout_spectrum: 0.78631
typography_spectrum: 0.85136
title: 'JJTS Web Streaming & Broadcast'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70674872-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001295'
    - '#405cfe'
    - '#f0f2fe'
    - '#7a87f9'
    - '#404560'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
